name: finance_tracker
description: A personal finance tracker app with local SQLite database.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.8.3
  intl: ^0.18.1
  fl_chart: ^0.66.0
  google_fonts: ^6.1.0
  iconsax: ^0.0.8
  uuid: ^4.2.1
  shared_preferences: ^2.2.2
  flutter_slidable: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
